### ISSUE TITLE
Conan Package Support

### ISSUE THREAD

**Issue by uilianries** [Tessil/robin-map#13]
Hello,

Do you know about [Conan](https://conan.io)?

Conan is modern dependency and package manager for C/C++ and would be great if your library would be available via package manager for other developers.

All Conan packages are available on [Conan Center](https://bintray.com/conan/conan-center), where is possible search, install and upload any official Conan package.

As your project is header-only, people will not need to download manually each new release. Other header-only projects, as Catch2, are available on Conan Center.

We could support you writing a recipe and publishing your packages on Bintray.

If you have any questions, just ask :-)

Regards!

**Comment by Tessil** [comment]
Hello,

Yes, I have some plans to add this library, and probably some other of my libraries, to Conan.

I'm currently checking to add `tsl-hopscotch-map` (see [PR 44](https://github.com/Tessil/hopscotch-map/pull/44)) to see a bit the procedure. I'll check to add `tsl-robin-map` after that.


Thanks for your work on Conan,
Thibaut

**Comment by uilianries** [comment]
Nice! Both me and @danimtb are able to help you with Conan!

Regards!

**Comment by Tessil** [comment]
Hi,

Now that everything seems to work fine with `tsl-hopscotch-map`, I added all the necessary files in the [conan-tsl-robin-map](https://github.com/Tessil/conan-tsl-robin-map) repository (and also [conan-tsl-ordered-map](https://github.com/Tessil/conan-tsl-ordered-map)).

Should I submit it through the 'Add to Conan Center' in Bintray or leave into your hands?

Thanks,
Thibaut

**Comment by uilianries** [comment]
Hi! Great to hear about it!

Please, apply to include in Conan center directly by your Bintray account. Conan team your review your recipe and open an issue for any required change.

**Comment by Tessil** [comment]
I'll close the issue as the package has been added.

Thank you for your work,
Thibaut

**Comment by uilianries** [comment]
https://bintray.com/tessil/tsl/tsl-robin-map%3Atessil
