### ISSUE TITLE
very slow clustering

### ISSUE THREAD

**Issue by ktprime** [Tessil/robin-map#15]
I use the follow code to generate test data and insert into  robin_map.h, it's quite slow because of clustering.
but this is not happen in my hash_table
https://github.com/ktprime/ktprime/blob/master/hash_table6.hpp

static uint32_t get32rand()
{
	return (rand() ^ (rand() << 15u) ^ (rand() << 30u));
}

static uint64_t get64rand()
{
	return (((uint64_t)get32rand()) << 32) | get32rand();
}

int setRandTest(uint32_t size, std::vector<uint64_t>& rankdata)
{
	rankdata.reserve(size);

	uint32_t step = (get32rand() % 64 + 1);
	auto s = get64rand();
	auto k = s;
	for (size_t i = 0; i < size; i ++) {
		k ++;
		if (get32rand() % 1024 == 0)
			k += step;

		rankdata.emplace_back(k);
	}
}

tsl::robin_map <uint64_t, int, std::hash<uint64_t>> robin_hashmap;

std::vector<uint64_t> rand_data
setRandTest(1000* 2000, rand_data);
for (auto& v : rand_data)
	robin_hashmap[v] = 0;

**Comment by Tessil** [comment]
Hi,

I quickly tested with your code:
```c++
#include <chrono>
#include <cstdlib>
#include <iostream>
#include <vector>
#include <hash_table6.hpp>
#include <tsl/robin_map.h>


static uint32_t get32rand() {
    return (rand() ^ (rand() << 15u) ^ (rand() << 30u));
}

static uint64_t get64rand() {
    return (((uint64_t)get32rand()) << 32) | get32rand();
}

void setRandTest(uint32_t size, std::vector<uint64_t>& rankdata) {
    rankdata.reserve(size);

    uint32_t step = (get32rand() % 64 + 1);
    auto s = get64rand();
    auto k = s;
    for (size_t i = 0; i < size; i ++) {
        k ++;
        if (get32rand() % 1024 == 0)
            k += step;

        rankdata.emplace_back(k);
    }
}

int main() {
    std::vector<uint64_t> rand_data;
    setRandTest(1000* 2000, rand_data);
    
    
    tsl::robin_map<uint64_t, int> hash_map;
//     emilib3::HashMap<uint64_t, int> hash_map;
    
    auto start_insert = std::chrono::high_resolution_clock::now();
    for (auto& v : rand_data) {
        hash_map[v] = 1;
    }
    auto end_insert = std::chrono::high_resolution_clock::now();
    
    
    uint64_t sum = 0;
    auto start_find = std::chrono::high_resolution_clock::now();
    for (auto& v : rand_data) {
        sum += hash_map[v];
    }
    auto end_find = std::chrono::high_resolution_clock::now();
    
    std::cout << "Sum: " << sum << std::endl;
    std::cout << "Inserts: " 
              << std::chrono::duration_cast<std::chrono::microseconds>
                     (end_insert - start_insert).count() 
              << " μs" << std::endl;
    std::cout << "Find: " 
              << std::chrono::duration_cast<std::chrono::microseconds>
                     (end_find - start_find).count() 
              << " μs" << std::endl;
}
```

On my side with g++ 8.3, I have the following results for `tsl::robin_map`: `Inserts: 89404 μs` and `Find: 5414 μs`.
For `emilib3::HashMap<uint64_t, int>`: `Inserts: 63364 μs` and `Find: 5028 μs`.

If you encounter bad performances, check you hash, especially with integers where `libstdc++` uses a naive identity function. You can also try to change the [growth policy](https://github.com/Tessil/robin-map#growth-policy).
