### ISSUE TITLE
Rehash "down" support on erase

### ISSUE THREAD

**Issue by anton-povarov** [Tessil/robin-map#16]
Hello.

Are there any plans to support hashtable "shrink" on erases and reaching sufficiently low load_factor (like maybe 0.125) ?

**Comment by Tessil** [comment]
Hello,

I could add a `min_load_factor` similar to [`google::dense_hash_map`](https://github.com/sparsehash/sparsehash/blob/4cb924025b8c622d1a1e11f4c1e9db15410c75fb/src/sparsehash/dense_hash_map#L73) if it fits yours needs. I'll see to add that in the next few days/weeks depending on when I can find some time.

**Comment by anton-povarov** [comment]
Cool, thank you!

Basically the use case that i have is time-series, in the sense that data is coming in, and is inserted into robin_map, then after some time - it's no longer needed and is removed.
Absense of shirink is not a problem most of the time (as we get to some plateau of max size and live happily). But when there is a sudden surge of traffic - the table grows to super large sizes and stays there, essentially forever.

I guess the workaround could be to check size()/bucket_count() periodically and rehash manually, but feels like a hack :)

**Comment by Tessil** [comment]
Hi,

I created the necessary branch [min_load_factor](https://github.com/Tessil/robin-map/tree/min_load_factor) with a first draft. I still have some tests to do, I'll probably merge the branch this weekend.

The implementation doesn't shrink the map on `erase` operations as shrinking the map invalidates all the iterators. All the `erase` operations have to return the next iterator and there is no meaningful way to do that if we invalidate the iterators. The following code must continue to work without deleting the 5 first elements of the map even if we reach a low load factor:
```c++
assert(map.size() > 5); 
auto it = std::next(map.begin(), 5);
while(it != map.end()) {
    it = map.erase(it);
}
```

Instead the shrinking is done when inserting a new element after some erase occurs and the load factor is below the `min_load_factor()`.

**Comment by Tessil** [comment]
I merge the changes.

**Comment by anton-povarov** [comment]
Thanks! will give it a try.
