### ISSUE TITLE
while using the robin_pg_map, there was an error

### ISSUE THREAD

**Issue by cortree-kor** [Tessil/robin-map#26]
Hi, there was an error(SIGABORT) using robin_pg_map in my code .  below was the cause.

prime_growth_policy
/usr/local/include/tsl/robin_growth_policy.h:283

robin_growth_policy.h:283 => TSL_RH_THROW_OR_TERMINATE(std::length_error, "The hash table exceeds its maxmimum size."); 

The number of PRIMES in the prime_growth_policy is 40, if I add the number of primes, does the error resolve?

**Comment by Tessil** [comment]
Hello,

Yes, raising the number of primes will allow the table to grow larger on a 64-bit platform. It's not possible on a platform with a 32-bit `std::size`.

I raised the limit in the last commit. The previous limit was the maximum prime that fitted a 32-bit unsigned integer thus limiting the hash table to 4 294 967 291 elements. I raised the maximum number to 6 597 069 766 657 elements.

Thibaut
