### ISSUE TITLE
Ceral with robin-map

### ISSUE THREAD

**Issue by PcChip** [Tessil/robin-map#28]
Hi,

I'd like to use tsl::robin_map everywhere instead of the std maps, however I can't figure out how to serialize them with Cereal.  I saw your post about sparse_map but don't see the same serialize functions in robin - am I missing something?

Thanks for your help!

**Comment by Tessil** [comment]
Hello,

Unfortunately it isn't yet implemented in robin-map. I have added it to my TODO list but it may take some time as I have some other things to work on beforehand.

Thibaut

**Comment by Tessil** [comment]
Hi,

Sorry for the quite long delay. I started the implementation in the [serialization branch](https://github.com/Tessil/robin-map/tree/serialization). I still need to add some documentation before merging it to the master but everything should work.

Thibaut

**Comment by PcChip** [comment]
awesome work! thanks for working on this and updating the thread!

**Comment by Tessil** [comment]
I merged the changes, let me know if there is any problem.
