### ISSUE TITLE
clear() does not trigger rehash

### ISSUE THREAD

**Issue by michitux** [Tessil/robin-map#31]
I re-use an existing `robin_set` after calling `clear()`. When I profiled this code, I noticed that a lot of time was spent in the iterator. Consider the following example:

```cpp
tsl::robin_set<size_t> my_set;
my_set.min_load_factor(0.1f);

for (size_t i = 0; i < 50000000; ++i) {
	my_set.insert(i);
}

std::cout << "Inserted items" << std::endl;

my_set.clear();

for (size_t i = 0; i < 10; ++i) {
	my_set.insert(9999999);
	for (size_t j : my_set) {
		std::cout << "Iterating over " << j << std::endl;
	}
	my_set.clear();
}
```

I would have expected that the second loop is very fast. However, it needs time proportional to the number of items I have inserted previously. What seems to happen is that only an `erase()` triggers rehashing on the next insertion, while calling `clear()` does not trigger any rehashing. Is there any reason for this?

**Comment by Tessil** [comment]
Hi,

Effectively `clear()` doesn't reset the `bucket_count` in a way similar to most `std::unordered_map` implementations.

I added the `min_load_factor()` method after the initial release and didn't think about `clear()`. It would be better to reset the `bucket_count` if `min_load_factor` is > 0.0. I'll check to implement that but it may take some time as I'll not be home for a few weeks.

Thibaut

**Comment by ktprime** [comment]
most flat hash map clear function do not release memory as std::unordered map do.
hash map need a function like shrink_to_fit to reset memory.

**Comment by michitux** [comment]
@ktprime Calling `reserve(0)` releases the memory, you can specify the current size instead of `0` to fit the hash map to the current number of members, so it's not really a problem.

@Tessil No problem, it is easy to work around, it was just unexpected.

**Comment by Tessil** [comment]
Hello,

I fixed the bug in the last commit. Please let me know if there is any problem.
