### ISSUE TITLE
pointer to value and hashmap resize

### ISSUE THREAD

**Issue by zeyangl** [Tessil/robin-map#32]
Hi, I wonder if it is valid to store a pointer to mapped value. When will this pointer be invalidated? Does map resize trigger an invalidation? Thanks.

**Comment by Tessil** [comment]
Hello,

Any operation modifying the hash map may unfortunately invalidate any pointer to the values of the hash map.

If you need pointer-stability, even in case of rehash, it would be better to use a node-based hash map.
