### ISSUE TITLE
Member function value() for non-const iterator possibly should be const

### ISSUE THREAD

**Issue by Predelnik** [Tessil/robin-map#33]
In most of the standard containers constness of iterator functions determined by - is iterator continues to point to the same element or not. So `operator*` of non-const iterator is `const` even if you can change underlying value through it.

TLDR: following should compile imo:
```cpp
tsl::robin_map<int, int> v = {{0, 0}};
const auto it = v.begin ();
it.value () = 1;
```

**Comment by Tessil** [comment]
Hi,

Effectively it makes sense, I fixed it in the last commit.
