### ISSUE TITLE
Compiling with "-Wshadow" flag causes error

### ISSUE THREAD

**Issue by stainleebakhla** [Tessil/robin-map#40]
Hi,

Compiling this with -Wshadow flag causes it to error out. If I set the -Wno-shadow flag, compilation passes successfully.

Currently I'm trying it to include it in a project of mine, but I'm not allowed to change any compilation flags. Would be really helpful if this problem could be solved.

Thanks
Stainlee

**Comment by stainleebakhla** [comment]
Willing to create a PR for this

**Comment by stainleebakhla** [comment]
Opened a PR: https://github.com/Tessil/robin-map/pull/41

**Comment by Tessil** [comment]
PR merged, closing.
