### ISSUE TITLE
Question: fixed memory?

### ISSUE THREAD

**Issue by jwdevel** [Tessil/robin-map#42]
I need a hash set in a constrained system where I cannot allocate memory; I have a fixed block available for the hash set, and that's it.

I *think* this is supported by robin-map, but I just wanted to confirm, and see if I understand the proper way.

The following is what I have in mind:

* Provide a custom allocator which just returns the singular block of memory I have available.
* Provide a custom growth policy, which just sets `min_bucket_count_in_out` to the max value I can support (though apparently I need to leave it 0 if it comes in as 0; not sure why)
  * In this policy, `next_bucket_count()` == `max_bucket_count()` == the same value I set `min_bucket_count_in_out` to in the constructor.

Does that seem right?

**Comment by Tessil** [comment]
Yes, a custom allocator and an eventual custom growth policy should work.

The growth policy requires to support zero bucket as a moved hash set will need to have zero bucket and still be in a valid state. The restriction of leaving a growth policy created with zero bucket to zero might be a bit too restrictive as `GrowthPolicy::clear` is used to reset the policy and not `GrowthPolicy(0)`. I will have to check if I can safely remove this restriction.
