### ISSUE TITLE
serialization using boost

### ISSUE THREAD

**Issue by jingpengw** [Tessil/robin-map#44]
currently, it requires that the serializer have an operator `()`, but boost serialization does not have that function.

```
error: type 'boost::archive::text_oarchive' does not provide a call operator.
```

my code is something like this:
```
template<class Archive>
void save(Archive& ar, const unsigned int version) const {
    mymap.serialize(ar);
}
```

Am I not using it correctly?
if not, would you like to consider supporting this?

**Comment by Tessil** [comment]
You have to wrap it in a lambda. Have you checked https://github.com/Tessil/robin-map#serialization-with-boost-serialization-and-compression-with-zlib? It should be easily adaptable to what you need.
