### ISSUE TITLE
CMake exports using incorrect name

### ISSUE THREAD

**Issue by david-cortes** [Tessil/robin-map#45]
Trying to add robin-map into a cmake script of another package using `find_package`, with the outputs generated by the cmake script of this project, throws this error:
```
...
find_package(tsl-robin-map PATHS "<my path>")
if (tsl-robin-map_FOUND)
    target_link_libraries(my_project PRIVATE tsl::robin-map)
endif()
```
```
CMake Error at <my path>/robinmap/build/tsl-robin-mapConfig.cmake:31 (include):
  include could not find load file:

    <my path>/robinmap/build/tsl-robin-mapTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:71 (find_package)


CMake Error at <my path>/robinmap/build/tsl-robin-mapConfig.cmake:32 (get_target_property):
  get_target_property() called with non-existent target "tsl::robin_map".
```

**Comment by Tessil** [comment]
The `find_package(tsl-robin-map PATHS "<my path>")` and `target_link_libraries(my_project PRIVATE tsl::robin-map)` lines seem to work fine after installing the package using `cmake -DCMAKE_INSTALL_PREFIX:PATH="<my_path>" ..` and `make install`. How did you install the package?

Note that there is a typo in the `target_link_libraries` of your cmake script. It should be `tsl::robin_map` and not `tsl::robin-map`.

**Comment by david-cortes** [comment]
I did not run a `make install`, but rather this:
```
cmake ..
cmake --build .
```

Then supplied the `/build` path to the cmake script where I wanted to use it.

Tried different spellings such as `tsl::robin_map`, but still get the same error.

This is under debian linux with cmake 3.18.4-2.

**Comment by Tessil** [comment]
If you don't install the package you can use:
```
add_subdirectory(path_to_robin_map_project)
target_link_libraries(your_target PRIVATE tsl::robin_map)  
```

**Comment by david-cortes** [comment]
That throws a different error:
```
CMake Error at CMakeLists.txt:12 (add_subdirectory):
  add_subdirectory not given a binary directory but the given source
  directory <path to robin> is not a subdirectory of
  <path to my project>.  When specifying an out-of-tree source
  a binary directory must be explicitly specified.
```

Works correctly with `sudo make install` + `find_package` though.

BTW other header-only libraries would still work by using `find_package` specifying a path from a build which underwent `cmake --build .` but didn't undergo `make install`. For example, `eigen` would still work under such a setting. Not sure what they do differently though.

**Comment by Tessil** [comment]
When using an out-of-tree source directory with `add_subdirectory` you need to also pass a `binary_dir` to specify where to store the output files.

Regarding the `find_package` I'll have to check as currently the `tsl-robin-mapConfig.cmake`, `tsl-robin-mapTargets.cmake` and `tsl-robin-mapConfigVersion.cmake` files are created during the installation process (see [CMakeLists.txt](https://github.com/Tessil/robin-map/blob/a603419b9a0687c9148e02c8bd5e3db180bb9ac0/CMakeLists.txt#L45)).

**Comment by Tessil** [comment]
Sorry for the delay, using `find_package` with the CMake binary directory should now work. Please let me know if you encounter any problem.
