### ISSUE TITLE
how to write range based for 

### ISSUE THREAD

**Issue by qdztxc** [Tessil/robin-map#47]
For iterators of tsl::robin_map, operator*() and operator->() return a reference and a pointer to const std::pair<Key, T> instead of std::pair<const Key, T> making the value T not modifiable. To modify the value you have to call the value() method of the iterator to get a mutable reference. 
------------
This is very convenient, all user code has to change to adopt this.
Besides is there a way to write ranged based for which is recommended for modern c++?
tsl::robin_map<int, int> map = {{1, 1}, {2, 1}, {3, 1}};
for(auto& it : map) {
    it.second = 2; // Illegal, any workaround??
} 

Is it a implementation or design choice for robin-map to use const std::pair<Key, T> instead of std::pair<const Key, T>?
Thanks and regards

**Comment by Tessil** [comment]
It's a conscious implementation choice, please check https://github.com/Tessil/ordered-map/issues/32 for more information.
