### ISSUE TITLE
release the latest version to conda-forge?

### ISSUE THREAD

**Issue by jingpengw** [Tessil/robin-map#49]
thank you for making this wonderful library.
I just found that the current release in conda-forge is from the date 06/22/2020. There are a lot of missing features, such as serialization. Would anyone like to help to release the latest version in conda-forge?

**Comment by mfansler** [comment]
(*conda-forge feedstock maintainer here*)

The new v1.0.0 [will be propagating out soon on Conda Forge](https://github.com/conda-forge/tsl_robin_map-feedstock/pull/6). For future reference, Conda Forge tracks GitHub Releases, so creating a _Release_ here is all that needs to happen to eventually push out there.

**Comment by Tessil** [comment]
Thank you for the reply.

Yes, this issue prompted me to create the 1.0.0 release but I didn't take the time to answer it as I wanted to solve https://github.com/Tessil/robin-map/issues/50 beforehand for which I could create a 1.0.1 release.

Sorry for the delay regarding the release, I'll close the issue then as conda-forge is up-to-date.
