### ISSUE TITLE
Broken on Conan

### ISSUE THREAD

**Issue by KenyonPrater** [Tessil/robin-map#53]
When installing OpenImageIO I get `ERROR: Unable to find 'tsl-robin-map/0.6.1@tessil/stable' in remotes`

The link in readme.md seems to be down as well.

**Comment by Tessil** [comment]
Bintray has been shutdown, the package can now be found in the Conan Center where OpenImageIO can also be found: https://conan.io/center/tsl-robin-map

I have updated the link in the README, thank you for letting me know.
