### ISSUE TITLE
Consider using `inline constexpr` for the `PRIMES` and `MOD_PRIME` tables inside robin_growth_policy.h

### ISSUE THREAD

**Issue by jessey-git** [Tessil/robin-map#79]
Consider using `inline constexpr` for the `PRIMES` and `MOD_PRIME` tables inside robin_growth_policy.h

These 2 tables are defined as `static constexpr const` but the `static` means they are internal linkage and every translation unit that includes the robin_growth_policy.h header in some way (basically anything that uses the main robin types) will eventually duplicate these tables into the final executable.

 The proper, ODR-safe, way to define such tables inside headers is to use `inline constexpr` with C++17 onwards.

This can be demonstrated by printing out the address of e.g. the first element of the PRIMES array in various .cpp files. You will see a different address printed for each file.  If you use `inline constexpr` only 1 address will be printed and you should also notice a slight drop in the final executable size as well.

**Comment by Tessil** [comment]
Thanks, I dropped C++11 support of the library as it was mainly historical compatibility when the library was created and moved it to C++17.

I made changed the two table to `inline constexpr`.
